# Generated by Django 4.0.5 on 2022-06-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_uid_alter_useraddress_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
